set_property IOSTANDARD LVCMOS33 [get_ports {a_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MRESET]
set_property PACKAGE_PIN Y9 [get_ports MCLK]
set_property PACKAGE_PIN V12 [get_ports {abcdefgdec_n[7]}]
set_property PACKAGE_PIN W12 [get_ports {abcdefgdec_n[6]}]
set_property PACKAGE_PIN W10 [get_ports {abcdefgdec_n[5]}]
set_property PACKAGE_PIN W11 [get_ports {abcdefgdec_n[4]}]
set_property PACKAGE_PIN V9 [get_ports {abcdefgdec_n[3]}]
set_property PACKAGE_PIN V10 [get_ports {abcdefgdec_n[2]}]
set_property PACKAGE_PIN V8 [get_ports {abcdefgdec_n[1]}]
set_property PACKAGE_PIN W8 [get_ports {abcdefgdec_n[0]}]
set_property PACKAGE_PIN AA8 [get_ports {a_n[0]}]
set_property PACKAGE_PIN AB9 [get_ports {a_n[1]}]
set_property PACKAGE_PIN AB10 [get_ports {a_n[2]}]
set_property PACKAGE_PIN AB11 [get_ports {a_n[3]}]
set_property PACKAGE_PIN R18 [get_ports MRESET]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets stop_IBUF]


create_clock -period 20.000 -waveform {0.000 10.000} [get_ports MCLK]

set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports stop]
set_property PACKAGE_PIN N15 [get_ports start]
set_property PACKAGE_PIN P16 [get_ports stop]
