# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/student/inf3430/oblig1/shiftn/shiftn.cache/wt [current_project]
set_property parent.project_path M:/student/inf3430/oblig1/shiftn/shiftn.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  M:/student/inf3430/oblig1/oppg4/shiftn/dff.vhd
  M:/student/inf3430/oblig1/oppg4/shiftn/shiftn.vhd
}
read_xdc M:/student/inf3430/oblig1/shiftn/shiftn.srcs/constrs_1/new/shiftn_constraintsMclock.xdc
set_property used_in_implementation false [get_files M:/student/inf3430/oblig1/shiftn/shiftn.srcs/constrs_1/new/shiftn_constraintsMclock.xdc]

synth_design -top shiftn -part xc7z020clg484-1
write_checkpoint -noxdef shiftn.dcp
catch { report_utilization -file shiftn_utilization_synth.rpt -pb shiftn_utilization_synth.pb }
