# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/student/inf3430/oblig2/oppg4/project_4/project_4.cache/wt [current_project]
set_property parent.project_path M:/student/inf3430/oblig2/oppg4/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  M:/student/inf3430/oblig2/src/seg7_pkg.vhd
  M:/student/inf3430/oblig2/src/slowclock_ent.vhd
  M:/student/inf3430/oblig2/src/counter.vhd
  M:/student/inf3430/oblig2/src/seg7ctrl_ent.vhd
  M:/student/inf3430/oblig2/src/seg7_bdy.vhd
  M:/student/inf3430/oblig2/src/sloclock_rtl.vhd
  M:/student/inf3430/oblig2/src/decoder.vhd
  M:/student/inf3430/oblig2/src/regctrl_ent.vhd
  M:/student/inf3430/oblig2/src/seg7ctrl_beh.vhd
  M:/student/inf3430/oblig2/src/regs_ent.vhd
  M:/student/inf3430/oblig2/src/regctrl_rtl.vhd
  M:/student/inf3430/oblig2/src/regs_str.vhd
}
read_xdc M:/student/inf3430/oblig2/oppg4/project_4/project_4.srcs/constrs_1/new/constraintsx.xdc
set_property used_in_implementation false [get_files M:/student/inf3430/oblig2/oppg4/project_4/project_4.srcs/constrs_1/new/constraintsx.xdc]

synth_design -top regs -part xc7z020clg484-1
write_checkpoint -noxdef regs.dcp
catch { report_utilization -file regs_utilization_synth.rpt -pb regs_utilization_synth.pb }
