# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/student/inf3430/oblig2/oppg5/stopwatch/stopwatch.cache/wt [current_project]
set_property parent.project_path M:/student/inf3430/oblig2/oppg5/stopwatch/stopwatch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  M:/student/inf3430/oblig2/oppg5/teller_ent.vhd
  M:/student/inf3430/oblig2/oppg5/seg7_pkg.vhd
  M:/student/inf3430/oblig2/oppg5/slowclock_ent.vhd
  M:/student/inf3430/oblig2/oppg5/teller_rtl.vhd
  M:/student/inf3430/oblig2/oppg5/regctrl_ent.vhd
  M:/student/inf3430/oblig2/oppg5/sloclock_rtl.vhd
  M:/student/inf3430/oblig2/oppg5/seg7ctrl_ent.vhd
  M:/student/inf3430/oblig2/oppg5/seg7_bdy.vhd
  M:/student/inf3430/oblig2/oppg5/decoder.vhd
  M:/student/inf3430/oblig2/oppg5/counter.vhd
  M:/student/inf3430/oblig2/oppg5/regctrl_rtl.vhd
  M:/student/inf3430/oblig2/oppg5/seg7ctrl_beh.vhd
  M:/student/inf3430/oblig2/oppg5/clock_ent.vhd
  M:/student/inf3430/oblig2/oppg5/clock_rtl.vhd
}
read_xdc M:/student/inf3430/oblig2/oppg5/stopwatch/stopwatch.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files M:/student/inf3430/oblig2/oppg5/stopwatch/stopwatch.srcs/constrs_1/new/constraints.xdc]

synth_design -top clock -part xc7z020clg484-1
write_checkpoint -noxdef clock.dcp
catch { report_utilization -file clock_utilization_synth.rpt -pb clock_utilization_synth.pb }
